### ISSUE TITLE
gigasquid.mxnet - Missing 'cv2' installation comment

### ISSUE THREAD

**Issue by pedrorgirardi** [gigasquid/libpython-clj-examples#1]
Hi @gigasquid. Thank you for putting these examples together!

I tried to run the code in the `gigasquid.mxnet` namespace and it seems like the `cv2` package is missing.  I know very little about Python, but I believe it's just a matter of installing it with `pip install opencv-python` - at least that's what I did to get it working.

All that to say the MXNet example is missing an installation comment for the cv2 package. 😀

Thank you!

**Comment by gigasquid** [comment]
Ah thanks for letting me know. I'll add it :)

**Comment by gigasquid** [comment]
Added it in the last commit
