### ISSUE TITLE
Proper procedure to add new example?

### ISSUE THREAD

**Issue by raymond-w-ko** [gigasquid/libpython-clj-examples#10]
Hello,

I recently ported over pytorch's MNIST example and would like to add it to this repository. Is there anything in particular I should do?

https://github.com/raymond-w-ko/techniko/blob/mnist/src/techniko/mnist.clj

**Comment by gigasquid** [comment]
That's a really cool example! I was wondering how to handle the class thing with pytorch. 

The only thing I would suggest would be to rename the file to be `pytorch_mnist` to clarify. Other than, that I would be delighted to add the example to the repo. Thanks!
