### ISSUE TITLE
Pytorch example errors on Mac

### ISSUE THREAD

**Issue by agilecreativity** [gigasquid/libpython-clj-examples#13]
Hi @raymond-w-ko,
Thanks for your MR with Pytorch example.
I keep getting the following error when trying to evaluate and run the example.
I know you probably getting no errors as you are on Arch Linux (I am a big fan myself).

Do you know any work around with this error? Or have you tried it with MacOS by any chance?

```
  Traceback (most recent call last): File
   "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line
   425, in to return self._apply(convert) File
   "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line
   201, in _apply module._apply(fn) File
   "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line
   223, in _apply param_applied = fn(param) File
   "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line
   423, in convert return t.to(device, dtype if t.is_floating_point() else None,
   non_blocking) File
   "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 196, in
   _lazy_init _check_driver() File
   "/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py", line 94, in
   _check_driver raise AssertionError("Torch not compiled with CUDA enabled")
   AssertionError: Torch not compiled with CUDA enabled
```
I am putting it here so that someone may know ways around it.
I am still trying to find the solution for it.

So far I am seeing some discussion about it here.

https://github.com/pytorch/pytorch/issues/30664
https://discuss.pytorch.org/t/using-pytorch-on-mac-without-cuda/33206

**Comment by agilecreativity** [comment]
Just found some information form Pytorch web site.
We may need to install Pytorch for Mac from source.
See screenshot below:

<img width="920" alt="Screenshot 2020-02-29 15 56 35" src="https://user-images.githubusercontent.com/4092543/75614979-4e52b600-5b0c-11ea-803b-90fc0cdbf2ea.png">

**Comment by agilecreativity** [comment]
Will try to follow this instruction and see if I can run this example:

# Follow instructions at this URL: https://github.com/pytorch/pytorch#from-source

**Comment by raymond-w-ko** [comment]
I don't have a Mac, but I will try to see if I can replicate the original example and add the no CUDA option. I personally think it is not productive to do ML without some sort of GPU/TPU, so I didn't add the switch in the first place.

**Comment by agilecreativity** [comment]
@raymond-w-ko 
Thanks for a quick response.
I do know that we should be doing ML with GPUAPU.
I am wondering though why I can run the python example without any errors, but when trying to run your added example. I keep getting the above error.
So this maybe environmental issue.

e.g. as you can see from the following screen shot:
<img width="1622" alt="Screenshot 2020-02-29 17 38 04" src="https://user-images.githubusercontent.com/4092543/75616078-6598a000-5b1a-11ea-9cef-e1893b9d10ef.png">

I am new to Python's ecosystem, so would love to be able to run it using the Mac.
Looking forward to your finding.

Thanks

**Comment by raymond-w-ko** [comment]
The pytorch example falls back to CPU if CUDA is not available I think https://github.com/pytorch/examples/blob/master/mnist/main.py#L93

I created a pull request that adds a switch in the form of a dynamic var, so if you set it to false, you should be able to run it on your Mac.

**Comment by raymond-w-ko** [comment]
#15

**Comment by agilecreativity** [comment]
See: https://github.com/gigasquid/libpython-clj-examples/pull/15#issuecomment-593003251
I did try this out using your branch in the MR. #15

**Comment by agilecreativity** [comment]
We know that for Mac OS, one must set the value of `*use-cuda*` to false, so that the example will work properly. This issue should now be resolved. Please see the discussion in the MR for details.
