### ISSUE TITLE
Include requirements.txt or pip freeze output? 

### ISSUE THREAD

**Issue by jjtolton** [gigasquid/libpython-clj-examples#19]
Hi @gigasquid!  Can you possibly include a `pip freeze` or a `requirements.txt` of your Python env so we can play with your great examples? Thank you!! --Jay

**Comment by gigasquid** [comment]
Sure - I put it on a requirements branch https://github.com/gigasquid/libpython-clj-examples/blob/requirements/requirements.txt because it has some extra stuff in there too

**Comment by jjtolton** [comment]
w00t!
